baseURL = "https://blog.jamesclonk.io/"
title = "Ramblings about all things technical"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "m10c"
paginate = 5
enableEmoji= true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Fabio Berchtold"
  description = "Working with tech is fun!"
  avatar = "https://avatars.githubusercontent.com/u/3172084?v=4"
  menu_item_separator = " - "
  favicon = "https://jamesclonk.io/favicon.ico"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/JamesClonk"

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#578acc"
