baseURL = "https://blog.jamesclonk.io/"
title = "Ramblings about all things technical"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "m10c"
paginate = 9
enableEmoji= true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    #style = "doom-one"
    #style = "github"
    #style = "lovelace"
    style = "tango"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Fabio Berchtold"
  description = "Working with tech is fun!"
  avatar = "/images/fabio_berchtold.jpg"
  menu_item_separator = " - "
  favicon = "https://jamesclonk.io/favicon.ico"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/JamesClonk"

# dark theme, use together with "doom-one" highlight
#  [params.style]
#    darkestColor = "#242930"
#    darkColor = "#353b43"
#    lightColor = "#afbac4"
#    lightestColor = "#ffffff"
#    primaryColor = "#578acc"

# light theme, use together with "tango" highlight
# "215580", "#1e4d73", "#1b4466", "#1a4162", "#133048", "#122d45"
  [params.style]
    darkestColor = "#f3f3f3"
    darkColor = "#ffffff"
    lightColor = "#333333"
    lightestColor = "#133048"
    primaryColor = "#215580"
